import { createContext } from 'react'

const ProductData =createContext([
    {  id:1,
       heading:"BLOOD WALA BHAIYA",
       imgSrc:"https://www.redpositive.in/images/blood_gif.gif",
       subHeading1:"‘Helping Life, Win Battles’", 
       subHeading1Des:"Will maintain a real time database of Blood Banks, Hospitals and Donors. Needy Recipient will be contacted and connected instantly with the potential Donor through mobile application",  
       subHeading3:"NEED BLOOD? Go to blood wale bhaiyya app", 
       subHeading3Img:"https://www.redpositive.in/images/blood1.png",
       subHeading4:"HOW? By connecting dots", 
       subHeading4Img1:"https://www.redpositive.in/images/dots1.png", 
       subHeading4Img2:"https://www.redpositive.in/images/dots2.png", 
       subHeading4Img3:"https://www.redpositive.in/images/dots3.png", 
       subHeading4Img4:"https://www.redpositive.in/images/dots4.png",  
       subHeading4Img4:"https://www.redpositive.in/images/dots4.png",  
       arrowImg:"https://www.redpositive.in/images/arrow.png",  
       subHeading5:"MINIMIZING THE BLOOD TRANSMISSION TIME", 

    },
    {  id:2,
       heading:"THE IT STUDIO",
       imgSrc:"https://www.redpositive.in/images/it_gif.gif",
       subHeading1:"‘Technology is the best when it comes to people together’",
       subHeading1Des:"Projects deal with e-commerce and end-to-end delivery of services via user-friendly applications. Our team consists of experienced full-stack developers, Android developers, and iOS developers.",
       subHeading1Img1:"https://www.redpositive.in/images/studio1.png", 
       subHeading1Img2:"https://www.redpositive.in/images/studio2.png", 
       subHeading1Img3:"https://www.redpositive.in/images/studio3.png", 
       subHeading1Img4:"https://www.redpositive.in/images/studio4.png", 
    },
    {  id:3,
       heading:"AI BASED DEFENCE SURVEILLANCE SYSTEM",
       imgSrc:"https://www.redpositive.in/images/defence_gif.gif",
       subTitle:"‘Scale up security, less down the crime rate’",
       subTitleDes:"A centralised surveillance system for search/defence/offense operations to identify the people and objects by use of face detection and object detection technology.       ",
       subHeading1:"Object detection", 
       subHeading1Des:`The Object Detection module will identify entities like aircrafts, tanks, landmines etc. and will annotate them with relevant tags like "ally", "enemy", "suspicious" etc. It will also provide information related to the current position and expected trajectory of the entity from CCTVs, satellite, and live feeds from UAVS.`, 
       subHeading1Img1:"https://www.redpositive.in/images/object1.png", 
       subHeading1Img2:"https://www.redpositive.in/images/object2.png", 
       subHeading1Img3:"https://www.redpositive.in/images/object3.png", 
       subHeading1Img4:"https://www.redpositive.in/images/object4.png", 
       subHeading2:"Face detection", 
       subHeading2Des:`The Face Recognition module will identify people and tag them as "ally", "enemy". "suspicious", "civilian" etc. It will also provide other specific details like name, age, profession etc. related to the person (if present in Database).`,
       subHeading2Img1:"https://www.redpositive.in/images/face1.png", 
       subHeading2Img2:"https://www.redpositive.in/images/face2.png", 
       subHeading2Img3:"https://www.redpositive.in/images/face3.png", 
       subHeading2Img4:"https://www.redpositive.in/images/face4.png",  
    },
    {  id:4,
       heading:"MACHINE AIDED LANGUAGE TRANSLATOR",
       imgSrc:"https://www.redpositive.in/images/machine_gif.gif",
       subTitle:"‘Create Translate Communicate’",
       subHeading1:"Language translator", 
       subHeading1Img1:"https://www.redpositive.in/images/language1.png", 
       subHeading1Img2:"https://www.redpositive.in/images/language2.png", 
       subHeading1Img3:"https://www.redpositive.in/images/language3.png", 
       subHeading1Img4:"https://www.redpositive.in/images/language4.png", 
    },
])

export default ProductData
